### ISSUE TITLE
Locale in custom provider

### ISSUE THREAD

**Issue by SchmidtClaudia** [KnpLabs/rad-fixtures-load#33]
```yml
my_bundle.my_provider:
    class: My\Provider
    tags:
        - { name: knp_rad_fixtures_load.provider }
```

How do I get the locale in my custom provider or do I need to register multiple services for different languages? Any arguments I can use?
